# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::114660512486:role/eksctl-eksctl-demo-nodegroup-ng-9-NodeInstanceRole-S3WQZKVBE5GD
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::114660512486:role/WinchyFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-11T11:16:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1631"
  uid: 86402a4e-a9ff-4721-8c24-f0c4258f7440
